In [1]:
import pandas as np

In [2]:
pred = np.read_csv("te.csv")

In [17]:
pred.head()

,patient_id,patient_race,payer_type,patient_state,patient_zip3,Region,Division,patient_age,patient_gender,bmi,...,Average of Jun-18,Average of Jul-18,Average of Aug-18,Average of Sep-18,Average of Oct-18,Average of Nov-18,Average of Dec-18,metastatic_diagnosis_period_pred_gbr,metastatic_diagnosis_period_pred_nn,metastatic_diagnosis_period_pred_pytorch
0,730681,NaN,COMMERCIAL,LA,713,South,West South Central,55,F,NaN,...,81.96,83.58,82.22,80.20,69.73,53.14,51.34,246.021054,227.689090,217.74577
1,334212,Black,NaN,NC,283,South,South Atlantic,60,F,40.00,...,80.05,82.88,82.09,78.85,64.60,50.57,48.10,61.621862,128.390320,95.52185
2,571362,NaN,COMMERCIAL,TX,794,South,West South Central,54,F,32.33,...,82.45,82.44,80.77,72.16,59.31,48.25,42.13,211.657085,218.555850,212.35220
3,907331,NaN,COMMERCIAL,TN,373,South,East South Central,63,F,27.07,...,75.20,76.96,75.78,74.87,61.06,44.31,42.83,200.162269,212.003390,204.30650
4,208382,Asian,NaN,WA,980,West,Pacific,62,F,NaN,...,57.88,66.16,65.21,57.52,49.53,43.75,38.33,60.006816,63.342346,76.11600

In [3]:
pred.head()

,patient_id,patient_race,payer_type,patient_state,patient_zip3,Region,Division,patient_age,patient_gender,bmi,...,Average of Apr-18,Average of May-18,Average of Jun-18,Average of Jul-18,Average of Aug-18,Average of Sep-18,Average of Oct-18,Average of Nov-18,Average of Dec-18,metastatic_diagnosis_period_pred_meta
0,730681,NaN,COMMERCIAL,LA,713,South,West South Central,55,F,NaN,...,62.23,78.34,81.96,83.58,82.22,80.20,69.73,53.14,51.34,244.988850
1,334212,Black,NaN,NC,283,South,South Atlantic,60,F,40.00,...,58.14,77.26,80.05,82.88,82.09,78.85,64.60,50.57,48.10,61.549206
2,571362,NaN,COMMERCIAL,TX,794,South,West South Central,54,F,32.33,...,59.95,77.79,82.45,82.44,80.77,72.16,59.31,48.25,42.13,216.980070
3,907331,NaN,COMMERCIAL,TN,373,South,East South Central,63,F,27.07,...,53.50,71.31,75.20,76.96,75.78,74.87,61.06,44.31,42.83,197.433670
4,208382,Asian,NaN,WA,980,West,Pacific,62,F,NaN,...,46.25,56.92,57.88,66.16,65.21,57.52,49.53,43.75,38.33,58.981434

In [5]:
columns_to_keep = ['patient_id', 'metastatic_diagnosis_period_pred_meta']
df = pred[columns_to_keep]

In [6]:
df.to_csv('p12.csv', index=False)